server:
  port: 9999
  context-path: /client
spring:
  config:
    name: client
security:
  oauth2:
    client:
      client-id: test
      client-secret: test123
      token-name: access_token
      check-token-uri: http://localhost:8080/oauth/check_token
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      clientId: acme
      clientSecret: acmesecret
      tokenInfoUri: http://localhost:8080/oauth/check_token