security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: test
      client-secret: test123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      client-id: test
      client-secret: test123
      userInfoUri: http://localhost:8080/user
      userAuthorizationUri: http://localhost:8080/oauth/authorize
#      tokenInfoUri: http://localhost:8080/oauth/authorize
      tokenInfoUri: http://localhost:8080/oauth/check_token
#auth:
# server:
#  url: http://localhost:8080/oauth/check_token/
#  clientId: test
#  clientSecret: test123
#oauth2:
# resource:
#  userInfoUri: http://localhost:8080/user
server:
  port: 8088